Updating dbignite omop package references for import
databrickslabs/dbignite pull request #34
Opened 2023-10-10 13:19 UTC by zavoraad

2023-10-12 20:32 UTC, kermany approved these changes
LGTM 🚢

2023-10-12 20:38 UTC, kermany requested changes
tests are faiing

2023-10-16 14:16 UTC, zavoraad commented
@kermany FYI tests are now passing

2023-11-03 18:28 UTC, kermany approved these changes
LGTM

2023-11-03 18:28 UTC, merged